// Mock data for the PeleAI Backoffice

export const clients = [
  {
    id: "CLI001",
    name: "Startup Sahel",
    email: "contact@startupsahel.ci",
    phone: "+225 07 12 34 56 78",
    company: "Startup Sahel SARL",
    status: "active",
    totalProjects: 3,
    totalRevenue: 4500000,
    joinedAt: "2024-01-15",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "CLI002",
    name: "Mamadou Diallo",
    email: "mamadou@techivoire.com",
    phone: "+225 05 98 76 54 32",
    company: "Tech Ivoire",
    status: "active",
    totalProjects: 5,
    totalRevenue: 8750000,
    joinedAt: "2023-11-20",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "CLI003",
    name: "Aisha Koné",
    email: "aisha@beauteafricaine.ci",
    phone: "+225 01 23 45 67 89",
    company: "Beauté Africaine",
    status: "active",
    totalProjects: 2,
    totalRevenue: 2300000,
    joinedAt: "2024-02-28",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "CLI004",
    name: "Ousmane Traoré",
    email: "ousmane@agriplus.ci",
    phone: "+225 07 11 22 33 44",
    company: "Agri Plus CI",
    status: "pending",
    totalProjects: 1,
    totalRevenue: 0,
    joinedAt: "2024-03-10",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "CLI005",
    name: "Fatou Bamba",
    email: "fatou@modeabidjan.com",
    phone: "+225 05 55 66 77 88",
    company: "Mode Abidjan",
    status: "inactive",
    totalProjects: 4,
    totalRevenue: 6200000,
    joinedAt: "2023-08-05",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "CLI006",
    name: "Ibrahim Sanogo",
    email: "ibrahim@logistiqueci.com",
    phone: "+225 07 99 88 77 66",
    company: "Logistique CI",
    status: "active",
    totalProjects: 2,
    totalRevenue: 3800000,
    joinedAt: "2024-01-22",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "CLI007",
    name: "Aminata Coulibaly",
    email: "aminata@edutech.ci",
    phone: "+225 01 44 55 66 77",
    company: "EduTech CI",
    status: "active",
    totalProjects: 3,
    totalRevenue: 5100000,
    joinedAt: "2023-12-01",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "CLI008",
    name: "Youssouf Konaté",
    email: "youssouf@healthplus.ci",
    phone: "+225 05 22 33 44 55",
    company: "Health Plus",
    status: "pending",
    totalProjects: 1,
    totalRevenue: 0,
    joinedAt: "2024-03-15",
    avatar: "/placeholder.svg?height=40&width=40",
  },
]

export const projects = [
  {
    id: "PRJ001",
    name: "Site E-commerce Tech Ivoire",
    client: "Tech Ivoire",
    clientId: "CLI002",
    type: "Site Web",
    status: "in-progress",
    progress: 75,
    budget: 3500000,
    startDate: "2024-01-10",
    deadline: "2024-04-15",
    teamMembers: ["Junior", "Awa", "Moussa"],
  },
  {
    id: "PRJ002",
    name: "Application Mobile Beauté Africaine",
    client: "Beauté Africaine",
    clientId: "CLI003",
    type: "Application Mobile",
    status: "in-progress",
    progress: 45,
    budget: 5000000,
    startDate: "2024-02-01",
    deadline: "2024-05-30",
    teamMembers: ["Junior", "Koffi"],
  },
  {
    id: "PRJ003",
    name: "Refonte Site Startup Sahel",
    client: "Startup Sahel",
    clientId: "CLI001",
    type: "Site Web",
    status: "completed",
    progress: 100,
    budget: 2000000,
    startDate: "2023-11-15",
    deadline: "2024-01-30",
    teamMembers: ["Junior", "Awa"],
  },
  {
    id: "PRJ004",
    name: "Campagne Marketing Mode Abidjan",
    client: "Mode Abidjan",
    clientId: "CLI005",
    type: "Marketing Digital",
    status: "completed",
    progress: 100,
    budget: 1500000,
    startDate: "2023-10-01",
    deadline: "2023-12-31",
    teamMembers: ["Fatou", "Moussa"],
  },
  {
    id: "PRJ005",
    name: "Chatbot IA Logistique CI",
    client: "Logistique CI",
    clientId: "CLI006",
    type: "Solution IA",
    status: "in-progress",
    progress: 60,
    budget: 4000000,
    startDate: "2024-02-15",
    deadline: "2024-04-30",
    teamMembers: ["Junior", "Koffi", "Moussa"],
  },
  {
    id: "PRJ006",
    name: "Plateforme E-learning EduTech",
    client: "EduTech CI",
    clientId: "CLI007",
    type: "Application Web",
    status: "pending",
    progress: 10,
    budget: 6000000,
    startDate: "2024-03-20",
    deadline: "2024-08-31",
    teamMembers: ["Junior", "Awa", "Koffi"],
  },
  {
    id: "PRJ007",
    name: "Identité Visuelle Agri Plus",
    client: "Agri Plus CI",
    clientId: "CLI004",
    type: "Branding",
    status: "pending",
    progress: 0,
    budget: 800000,
    startDate: "2024-03-25",
    deadline: "2024-04-25",
    teamMembers: ["Fatou"],
  },
  {
    id: "PRJ008",
    name: "Application Santé Health Plus",
    client: "Health Plus",
    clientId: "CLI008",
    type: "Application Mobile",
    status: "pending",
    progress: 5,
    budget: 7500000,
    startDate: "2024-04-01",
    deadline: "2024-09-30",
    teamMembers: ["Junior", "Koffi", "Awa", "Moussa"],
  },
]

export const messages = [
  {
    id: "MSG001",
    from: "Mamadou Diallo",
    email: "mamadou@techivoire.com",
    subject: "Question sur le projet e-commerce",
    message: "Bonjour, j'aimerais savoir si nous pouvons ajouter une fonctionnalité de paiement mobile Money à la boutique en ligne. Merci de me tenir informé.",
    date: "2024-03-18T10:30:00",
    read: false,
    type: "client",
  },
  {
    id: "MSG002",
    from: "Aisha Koné",
    email: "aisha@beauteafricaine.ci",
    subject: "Validation des maquettes",
    message: "Bonjour Junior, les maquettes de l'application sont superbes ! J'ai quelques petites modifications à proposer. Pouvons-nous organiser un call cette semaine ?",
    date: "2024-03-17T14:45:00",
    read: false,
    type: "client",
  },
  {
    id: "MSG003",
    from: "Nouveau prospect",
    email: "info@hotelpalace.ci",
    subject: "Demande de devis - Site web hôtel",
    message: "Bonjour, nous sommes un hôtel 4 étoiles basé à Abidjan et nous recherchons une agence pour refaire notre site web avec système de réservation. Pouvez-vous nous envoyer un devis ?",
    date: "2024-03-16T09:15:00",
    read: true,
    type: "prospect",
  },
  {
    id: "MSG004",
    from: "Ibrahim Sanogo",
    email: "ibrahim@logistiqueci.com",
    subject: "Retour sur le chatbot",
    message: "Le chatbot fonctionne très bien ! Nos clients sont satisfaits. Merci à toute l'équipe PeleAI.",
    date: "2024-03-15T16:20:00",
    read: true,
    type: "client",
  },
  {
    id: "MSG005",
    from: "Demande via formulaire",
    email: "startup@newtech.ci",
    subject: "Intéressé par PeleAI360",
    message: "Bonjour, nous avons vu votre solution PeleAI360 et sommes très intéressés. Pouvons-nous avoir une démonstration ?",
    date: "2024-03-14T11:00:00",
    read: true,
    type: "demo",
  },
  {
    id: "MSG006",
    from: "Fatou Bamba",
    email: "fatou@modeabidjan.com",
    subject: "Nouveau projet",
    message: "Bonjour, nous souhaitons lancer une nouvelle campagne pour la collection été. Pouvez-vous nous faire une proposition ?",
    date: "2024-03-13T08:30:00",
    read: true,
    type: "client",
  },
]

export const teamMembers = [
  {
    id: "TM001",
    name: "Pelecho Junior Kone",
    role: "CEO & Lead Developer",
    email: "junior@peleai.ci",
    avatar: "/placeholder.svg?height=40&width=40",
    projects: 8,
    status: "online",
  },
  {
    id: "TM002",
    name: "Awa Diarra",
    role: "UI/UX Designer",
    email: "awa@peleai.ci",
    avatar: "/placeholder.svg?height=40&width=40",
    projects: 4,
    status: "online",
  },
  {
    id: "TM003",
    name: "Moussa Koné",
    role: "Marketing Manager",
    email: "moussa@peleai.ci",
    avatar: "/placeholder.svg?height=40&width=40",
    projects: 3,
    status: "offline",
  },
  {
    id: "TM004",
    name: "Koffi Assié",
    role: "Backend Developer",
    email: "koffi@peleai.ci",
    avatar: "/placeholder.svg?height=40&width=40",
    projects: 4,
    status: "online",
  },
  {
    id: "TM005",
    name: "Fatou Sylla",
    role: "Graphic Designer",
    email: "fatou.s@peleai.ci",
    avatar: "/placeholder.svg?height=40&width=40",
    projects: 2,
    status: "away",
  },
]

export const revenueData = [
  { month: "Jan", revenue: 4500000, expenses: 2100000 },
  { month: "Fév", revenue: 5200000, expenses: 2400000 },
  { month: "Mar", revenue: 4800000, expenses: 2200000 },
  { month: "Avr", revenue: 6100000, expenses: 2800000 },
  { month: "Mai", revenue: 5800000, expenses: 2600000 },
  { month: "Juin", revenue: 7200000, expenses: 3100000 },
  { month: "Juil", revenue: 6500000, expenses: 2900000 },
  { month: "Août", revenue: 5900000, expenses: 2700000 },
  { month: "Sep", revenue: 7800000, expenses: 3400000 },
  { month: "Oct", revenue: 8500000, expenses: 3800000 },
  { month: "Nov", revenue: 9200000, expenses: 4100000 },
  { month: "Déc", revenue: 10500000, expenses: 4600000 },
]

export const projectTypeData = [
  { type: "Site Web", count: 12, revenue: 18000000 },
  { type: "Application Mobile", count: 8, revenue: 28000000 },
  { type: "Marketing Digital", count: 15, revenue: 12000000 },
  { type: "Branding", count: 10, revenue: 8000000 },
  { type: "Solution IA", count: 5, revenue: 15000000 },
]

export const notifications = [
  {
    id: "NOT001",
    title: "Nouveau message",
    message: "Mamadou Diallo vous a envoyé un message",
    time: "Il y a 5 min",
    type: "message",
    read: false,
  },
  {
    id: "NOT002",
    title: "Projet terminé",
    message: "Le projet 'Refonte Site Startup Sahel' est terminé",
    time: "Il y a 2 heures",
    type: "success",
    read: false,
  },
  {
    id: "NOT003",
    title: "Deadline proche",
    message: "Le projet 'Site E-commerce Tech Ivoire' arrive à échéance dans 3 jours",
    time: "Il y a 1 jour",
    type: "warning",
    read: true,
  },
  {
    id: "NOT004",
    title: "Nouveau client",
    message: "Youssouf Konaté de Health Plus s'est inscrit",
    time: "Il y a 2 jours",
    type: "info",
    read: true,
  },
]

export const activities = [
  {
    id: "ACT001",
    user: "Pelecho Junior Kone",
    action: "a mis à jour le projet",
    target: "Site E-commerce Tech Ivoire",
    time: "Il y a 30 min",
  },
  {
    id: "ACT002",
    user: "Awa Diarra",
    action: "a uploadé de nouvelles maquettes pour",
    target: "Application Mobile Beauté Africaine",
    time: "Il y a 1 heure",
  },
  {
    id: "ACT003",
    user: "Koffi Assié",
    action: "a terminé une tâche sur",
    target: "Chatbot IA Logistique CI",
    time: "Il y a 2 heures",
  },
  {
    id: "ACT004",
    user: "Moussa Koné",
    action: "a créé une campagne pour",
    target: "Mode Abidjan",
    time: "Il y a 3 heures",
  },
  {
    id: "ACT005",
    user: "Fatou Sylla",
    action: "a finalisé le logo de",
    target: "Agri Plus CI",
    time: "Il y a 5 heures",
  },
]

export const invoices = [
  {
    id: "INV001",
    client: "Tech Ivoire",
    project: "Site E-commerce",
    amount: 1750000,
    status: "paid",
    dueDate: "2024-02-28",
    paidDate: "2024-02-25",
  },
  {
    id: "INV002",
    client: "Beauté Africaine",
    project: "Application Mobile",
    amount: 2500000,
    status: "pending",
    dueDate: "2024-04-15",
    paidDate: null,
  },
  {
    id: "INV003",
    client: "Startup Sahel",
    project: "Refonte Site",
    amount: 2000000,
    status: "paid",
    dueDate: "2024-01-30",
    paidDate: "2024-01-28",
  },
  {
    id: "INV004",
    client: "Logistique CI",
    project: "Chatbot IA",
    amount: 2000000,
    status: "overdue",
    dueDate: "2024-03-10",
    paidDate: null,
  },
  {
    id: "INV005",
    client: "EduTech CI",
    project: "Plateforme E-learning",
    amount: 3000000,
    status: "pending",
    dueDate: "2024-05-01",
    paidDate: null,
  },
]
